import React from 'react';
import { Link } from 'react-router-dom';
import { Code2, KeyRound, Play, Server, TerminalSquare } from 'lucide-react';
import { Navbar } from '../components/layout/Navbar';
import { Footer } from '../components/layout/Footer';

const quickStart = [
  ['1', 'Install dependencies', 'npm install'],
  ['2', 'Configure provider keys', 'OPENAI_API_KEY, OPENAI_BASE_URL, GITHUB_TOKEN'],
  ['3', 'Run the local app', 'npm run dev'],
  ['4', 'Open the workspace', 'http://localhost:3000'],
];

const endpoints = [
  ['GET', '/api/analyze', 'Streams repository analysis progress and final workspace data through SSE.'],
  ['GET', '/api/project/:id', 'Returns cached analysis data for a repository that has already completed.'],
  ['GET', '/api/project/:id/status', 'Returns pending, completed, or failed status with the current analysis step.'],
  ['POST', '/api/tutor', 'Answers context-aware questions from the active file, lesson, or module.'],
];

export default function Docs() {
  return (
    <div className="min-h-screen bg-[#09090B] flex flex-col">
      <div className="noise-overlay" />
      <Navbar />

      <main className="flex-1">
        <section className="px-4 md:px-8 py-24 md:py-32 max-w-[95vw] mx-auto">
          <p className="text-[#DFE104] font-bold uppercase tracking-widest mb-6">Docs</p>
          <h1 className="text-6xl md:text-[clamp(5rem,10vw,11rem)] font-bold uppercase tracking-tighter leading-[0.82] max-w-5xl">
            Build And Run OpenWiki
          </h1>
          <p className="text-xl md:text-2xl text-[#A1A1AA] uppercase tracking-wide max-w-3xl mt-10">
            A compact guide to the local workflow, environment variables, repository analysis API, and the workspace generated by OpenWiki.
          </p>
        </section>

        <section className="px-4 md:px-8 pb-24 max-w-[95vw] mx-auto grid grid-cols-1 lg:grid-cols-[0.8fr_1.2fr] gap-8">
          <div className="border-2 border-[#3F3F46] p-8 md:p-10 bg-[#111113]">
            <TerminalSquare className="text-[#DFE104] mb-10" size={48} strokeWidth={1.5} />
            <h2 className="text-4xl font-bold uppercase tracking-tighter mb-6">Quick Start</h2>
            <p className="text-[#A1A1AA] text-lg leading-relaxed">
              OpenWiki runs as an Express server with Vite middleware in development. Paste a public GitHub repository URL to start analysis.
            </p>
          </div>

          <div className="grid gap-px bg-[#3F3F46] border-2 border-[#3F3F46]">
            {quickStart.map(([step, title, command]) => (
              <div key={step} className="grid grid-cols-[4rem_1fr] gap-5 bg-[#09090B] p-6 items-center">
                <div className="text-[#DFE104] text-3xl font-bold">{step}</div>
                <div className="min-w-0">
                  <h3 className="text-2xl font-bold uppercase tracking-tighter">{title}</h3>
                  <p className="font-mono text-[#A1A1AA] text-sm md:text-base truncate mt-2">{command}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="px-4 md:px-8 pb-24 max-w-[95vw] mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="border-2 border-[#3F3F46] p-8 bg-[#09090B]">
            <KeyRound className="text-[#DFE104] mb-8" size={40} strokeWidth={1.5} />
            <h2 className="text-3xl font-bold uppercase tracking-tighter mb-4">Environment</h2>
            <p className="text-[#A1A1AA] leading-relaxed">Set `OPENAI_API_KEY`, `OPENAI_BASE_URL`, and optionally `GITHUB_TOKEN` for higher GitHub API limits.</p>
          </div>
          <div className="border-2 border-[#3F3F46] p-8 bg-[#09090B]">
            <Play className="text-[#DFE104] mb-8" size={40} strokeWidth={1.5} />
            <h2 className="text-3xl font-bold uppercase tracking-tighter mb-4">Analysis Steps</h2>
            <p className="text-[#A1A1AA] leading-relaxed">The loading page follows SSE steps from metadata fetch through source sampling, AI generation, validation, and finalization.</p>
          </div>
          <div className="border-2 border-[#3F3F46] p-8 bg-[#09090B]">
            <Code2 className="text-[#DFE104] mb-8" size={40} strokeWidth={1.5} />
            <h2 className="text-3xl font-bold uppercase tracking-tighter mb-4">Workspace Data</h2>
            <p className="text-[#A1A1AA] leading-relaxed">The frontend stores project, summary, file tree, modules, lessons, architecture, and business analysis in Zustand.</p>
          </div>
        </section>

        <section className="px-4 md:px-8 pb-32 max-w-[95vw] mx-auto">
          <div className="border-2 border-[#3F3F46]">
            <div className="p-6 md:p-8 bg-[#27272A] border-b-2 border-[#3F3F46] flex items-center gap-4">
              <Server className="text-[#DFE104]" size={36} strokeWidth={1.5} />
              <h2 className="text-4xl md:text-5xl font-bold uppercase tracking-tighter">API Surface</h2>
            </div>
            <div className="grid gap-px bg-[#3F3F46]">
              {endpoints.map(([method, path, desc]) => (
                <div key={path} className="grid grid-cols-1 md:grid-cols-[8rem_18rem_1fr] gap-4 bg-[#09090B] p-6">
                  <span className="text-[#DFE104] font-bold uppercase">{method}</span>
                  <span className="font-mono text-[#FAFAFA] break-all">{path}</span>
                  <span className="text-[#A1A1AA]">{desc}</span>
                </div>
              ))}
            </div>
          </div>
          <Link to="/product" className="inline-block mt-8 text-[#DFE104] font-bold uppercase tracking-widest hover:text-white transition-colors">
            See product overview
          </Link>
        </section>
      </main>

      <Footer />
    </div>
  );
}
